// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InsuranceQuotingSystemTestsTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void iQTC01InsuranceQuote01ValidInput() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04//prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(973, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("365 Albert St");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("24");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.Id("finalQuote")).Text, Is.EqualTo("$5500"));
  }
  [Test]
  public void iQTC02InsuranceQuote02Refused() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(973, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("amarnath");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("4");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector(".container")).Click();
    Assert.That(driver.FindElement(By.Id("finalQuote")).Text, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
  }
  [Test]
  public void iQTC03InsuranceQuote03ReducedRate() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("9");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("finalQuote")).Text, Is.EqualTo("$3905"));
  }
  [Test]
  public void iQTC04InsuranceQuote04InvalidPhone() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(973, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("22689849");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("27");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
  }
  [Test]
  public void iQTC05InsuranceQuote05InvalidEmail() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("28");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("addForm")).Click();
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.Id("email-error")).Click();
    Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
  }
  [Test]
  public void iQTC06InsuranceQuote06InvalidPostalCode() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(682, 649);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("postalCode")).Click();
    driver.FindElement(By.Id("postalCode")).SendKeys("NBD123");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("15");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.CssSelector(".card-body")).Click();
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector(".col-md-2")).Click();
    Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
  }
  [Test]
  public void iQTC07InsuranceQuote07OmittedAge() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(682, 649);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("5");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
  }
  [Test]
  public void iQTC08InsuranceQuote08OmittedAccidents() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("37");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("8");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.Id("accidents-error")).Click();
    driver.FindElement(By.Id("accidents-error")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
  }
  [Test]
  public void iQTC09InsuranceQuote09OmittedExperience() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("40");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
  }
  [Test]
  public void iQTC10InsuranceQuote10YoungDriverReduction() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("15");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("22");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
  }
  [Test]
  public void iQTC11InsuranceQuote11ExperiencedDriverReduction() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("30");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("35");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("No Insurance for you!! Driver Age / Experience Not Correct"));
    }
  }
  [Test]
  public void iQTC12InsuranceQuote12AgeExperienceValidation() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(682, 649);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("46");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("30");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$2840"));
    }
  }
  [Test]
  public void iQTC13InsuranceQuote13BoundaryAge() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("40");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("5");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
    }
  }
  [Test]
  public void iQTC14InsuranceQuote14BoundaryExperience() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("address")).SendKeys("U683, Floor 8, 365-6 Albert St");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("32");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("2");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$3905"));
    }
  }
  [Test]
  public void iQTC15InsuranceQuote15InvalidAddress() {
    driver.Navigate().GoToUrl("http://localhost/prog8171a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(973, 1032);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Amarnath");
    driver.FindElement(By.Id("lastName")).SendKeys("Kathiresan");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 0G7");
    driver.FindElement(By.Id("phone")).SendKeys("2268984990");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("226-898-4990");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("k.amarnath7@gmail.com");
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("45");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.Id("btnSubmit")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    Assert.That(driver.FindElement(By.Id("address-error")).Text, Is.EqualTo("Address is required"));
  }
}
